lagunage: go
go:
    - 1.9
    - 1.10.x
    - master
install:
    - export SOURCE=`pwd`

script:
    - make test build

before_deploy:
    - make compile

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    skip-cleanup: true
    file_glob: true
    file: $SOURCE/target/*
    on:
      tags: true
