lagunage: go
go:
    - 1.9
    - 1.8
    - master
install:
    - mkdir -p $GOPATH/src/github.com/sikong-mq/
    - cp skmq $GOPATH/src/github.com/sikong-mq/ -r
    - cp vendor/* $GOPATH/src/ -r
script:
    - go test -v -race ./skmq/...
    - go vet ./...